name: Terraform 

on:
  push:
    branches:
      - main

jobs:

  terraform:
  
    runs-on: ubuntu-latest
    fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Run Terraform
      continue-on-error: true
      run: |
        terraform init
        terraform fmt -check || true
        terraform plan
        terraform apply -auto-approve
        
    - name: Check Exit Code  
      if: ${{ failure() }}
      run: exit 1
        
    - name: Upload Logs
      uses: actions/upload-artifact@v2
      with: 
        name: logs
        path: |
          *.log
          *.out
          
  logs-retention:

    needs: terraform 
    runs-on: ubuntu-latest

    steps:
    
    - name: Set Retention Period
      uses: actions/upload-artifact@v2
      with:
        retention-days: 3
